import asyncio
import os
from app.database import connect_to_mongo, close_mongo_connection
from app.services.user_service import create_user

async def create_admin():
    print("Connecting to database...")
    await connect_to_mongo()
    
    try:
        # Test Data
        email = "admin@example.com"
        password = "adminpassword123"
        full_name = "System Admin"
        
        # In a real scenario, these should be generated by the frontend crypto lib
        # Providing dummy values for testing purposes
        key_salt = "test_salt_123456789"
        encrypted_master_key = "test_encrypted_key_abc123" 

        print(f"Creating user: {email}")
        user = await create_user(
            email=email,
            full_name=full_name,
            password=password,
            key_salt=key_salt,
            encrypted_master_key=encrypted_master_key
        )
        print(f"✓ User created successfully!")
        print(f"ID: {user['id']}")
        print(f"Email: {user['email']}")
        
    except ValueError as e:
        print(f"⚠ Error: {e}")
    except Exception as e:
        print(f"✗ Unexpected error: {e}")
    finally:
        await close_mongo_connection()

if __name__ == "__main__":
    asyncio.run(create_admin())