import React, { useState } from 'react';

function ManageAnalysts() {
  // Mock data for analysts
  const [analysts, setAnalysts] = useState([
    { id: 1, name: 'Alex Security', email: 'alex.s@cloudshield.local', role: 'Analyst', status: 'Active', lastLogin: '2 hours ago' },
    { id: 2, name: 'Jordan Rivera', email: 'jordan.r@cloudshield.local', role: 'Senior Analyst', status: 'Active', lastLogin: '1 day ago' },
    { id: 3, name: 'Casey Smith', email: 'casey.s@cloudshield.local', role: 'Analyst', status: 'Suspended', lastLogin: '2 weeks ago' },
  ]);

  // Mock data for Activity Logs (Audit Trail)
  // In a real application, these would be generated by the backend when an analyst logs in or clicks "Acknowledge/Resolve" on the Alerts page.
  const [activityLogs] = useState([
    { id: 101, analystId: 1, type: 'login', action: 'System Login', timestamp: 'Today, 08:00 AM', details: 'IP: 192.168.1.50' },
    { id: 102, analystId: 1, type: 'acknowledge', action: 'Acknowledged Alert', timestamp: 'Today, 08:15 AM', details: 'Alert ID: #45 - SYN Flood Detected' },
    { id: 103, analystId: 1, type: 'resolve', action: 'Resolved Alert', timestamp: 'Today, 08:45 AM', details: 'Alert ID: #45 - Applied IP Block' },
    { id: 104, analystId: 1, type: 'logout', action: 'System Logout', timestamp: 'Today, 12:00 PM', details: 'Session duration: 4h 0m' },
    
    { id: 201, analystId: 2, type: 'login', action: 'System Login', timestamp: 'Yesterday, 09:00 AM', details: 'IP: 192.168.1.62' },
    { id: 202, analystId: 2, type: 'system', action: 'Updated Suricata Rule', timestamp: 'Yesterday, 10:30 AM', details: 'Rule SID: 2001234' },
    { id: 203, analystId: 2, type: 'acknowledge', action: 'Acknowledged Alert', timestamp: 'Yesterday, 11:15 AM', details: 'Alert ID: #12 - UDP Amplification' },
  ]);

  // Modals State
  const [showAddModal, setShowAddModal] = useState(false);
  const [newAnalyst, setNewAnalyst] = useState({ name: '', email: '', role: 'Analyst' });
  
  const [showActivityModal, setShowActivityModal] = useState(false);
  const [selectedAnalyst, setSelectedAnalyst] = useState(null);

  // --- Handlers ---
  const handleToggleStatus = (id) => {
    setAnalysts(analysts.map(analyst => {
      if (analyst.id === id) {
        return { ...analyst, status: analyst.status === 'Active' ? 'Suspended' : 'Active' };
      }
      return analyst;
    }));
  };

  const handleDelete = (id) => {
    if (window.confirm('Are you sure you want to remove this analyst? This action cannot be undone.')) {
      setAnalysts(analysts.filter(a => a.id !== id));
    }
  };

  const handleAddSubmit = (e) => {
    e.preventDefault();
    if (!newAnalyst.name || !newAnalyst.email) return;

    const newId = analysts.length > 0 ? Math.max(...analysts.map(a => a.id)) + 1 : 1;
    setAnalysts([...analysts, { 
      id: newId, 
      ...newAnalyst, 
      status: 'Active', 
      lastLogin: 'Never' 
    }]);
    
    setNewAnalyst({ name: '', email: '', role: 'Analyst' });
    setShowAddModal(false);
  };

  const openActivityLog = (analyst) => {
    setSelectedAnalyst(analyst);
    setShowActivityModal(true);
  };

  // Utility to style log types
  const getLogStyle = (type) => {
    const styles = {
      login: { color: '#4caf50', icon: '🟢' },
      logout: { color: '#9e9e9e', icon: '⭕' },
      acknowledge: { color: '#2196F3', icon: '👀' },
      resolve: { color: '#ed6c02', icon: '✅' },
      system: { color: '#9c27b0', icon: '⚙️' }
    };
    return styles[type] || { color: '#666', icon: '📝' };
  };

  return (
    <div style={{ padding: '2rem', maxWidth: '1200px', margin: '0 auto', fontFamily: 'sans-serif' }}>
      
      {/* Header section */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2rem' }}>
        <div>
          <h1 style={{ margin: 0, color: '#333' }}>Manage Analysts</h1>
          <p style={{ margin: '0.5rem 0 0 0', color: '#666' }}>Add, remove, and monitor activity for SOC analysts.</p>
        </div>
        <button 
          onClick={() => setShowAddModal(true)}
          style={{ padding: '0.75rem 1.5rem', backgroundColor: '#2196F3', color: 'white', border: 'none', borderRadius: '6px', cursor: 'pointer', fontWeight: 'bold', display: 'flex', alignItems: 'center', gap: '0.5rem', transition: 'background 0.2s' }}>
          <span>➕</span> Add New Analyst
        </button>
      </div>

      {/* Analysts Table */}
      <div style={{ backgroundColor: '#fff', borderRadius: '10px', boxShadow: '0 4px 12px rgba(0,0,0,0.05)', overflow: 'hidden' }}>
        <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left' }}>
          <thead style={{ backgroundColor: '#f8f9fa', borderBottom: '2px solid #eee' }}>
            <tr>
              <th style={{ padding: '1rem 1.5rem', color: '#555', fontWeight: '600' }}>Name</th>
              <th style={{ padding: '1rem 1.5rem', color: '#555', fontWeight: '600' }}>Email</th>
              <th style={{ padding: '1rem 1.5rem', color: '#555', fontWeight: '600' }}>Role</th>
              <th style={{ padding: '1rem 1.5rem', color: '#555', fontWeight: '600' }}>Status</th>
              <th style={{ padding: '1rem 1.5rem', color: '#555', fontWeight: '600' }}>Last Login</th>
              <th style={{ padding: '1rem 1.5rem', color: '#555', fontWeight: '600', textAlign: 'right' }}>Actions</th>
            </tr>
          </thead>
          <tbody>
            {analysts.map((analyst) => (
              <tr key={analyst.id} style={{ borderBottom: '1px solid #eee', transition: 'background-color 0.2s' }}>
                <td style={{ padding: '1rem 1.5rem', fontWeight: '500', color: '#222' }}>{analyst.name}</td>
                <td style={{ padding: '1rem 1.5rem', color: '#666' }}>{analyst.email}</td>
                <td style={{ padding: '1rem 1.5rem' }}>
                  <span style={{ backgroundColor: '#e3f2fd', color: '#1565c0', padding: '0.25rem 0.75rem', borderRadius: '15px', fontSize: '0.85rem', fontWeight: '500' }}>
                    {analyst.role}
                  </span>
                </td>
                <td style={{ padding: '1rem 1.5rem' }}>
                  <span style={{ 
                    display: 'inline-block',
                    width: '8px',
                    height: '8px',
                    borderRadius: '50%',
                    backgroundColor: analyst.status === 'Active' ? '#4caf50' : '#f44336',
                    marginRight: '0.5rem'
                  }}></span>
                  <span style={{ color: analyst.status === 'Active' ? '#333' : '#888' }}>{analyst.status}</span>
                </td>
                <td style={{ padding: '1rem 1.5rem', color: '#888', fontSize: '0.9rem' }}>{analyst.lastLogin}</td>
                <td style={{ padding: '1rem 1.5rem', textAlign: 'right' }}>
                  <button 
                    onClick={() => openActivityLog(analyst)}
                    style={{ padding: '0.4rem 0.8rem', marginRight: '0.5rem', backgroundColor: '#f0f4f8', border: '1px solid #cddc39', borderRadius: '4px', cursor: 'pointer', color: '#558b2f', fontWeight: '500' }}>
                    View Activity
                  </button>
                  <button 
                    onClick={() => handleToggleStatus(analyst.id)}
                    style={{ padding: '0.4rem 0.8rem', marginRight: '0.5rem', backgroundColor: 'transparent', border: '1px solid #ddd', borderRadius: '4px', cursor: 'pointer', color: '#555' }}>
                    {analyst.status === 'Active' ? 'Suspend' : 'Activate'}
                  </button>
                  <button 
                    onClick={() => handleDelete(analyst.id)}
                    style={{ padding: '0.4rem 0.8rem', backgroundColor: '#ffebee', border: '1px solid #ffcdd2', borderRadius: '4px', cursor: 'pointer', color: '#d32f2f' }}>
                    Remove
                  </button>
                </td>
              </tr>
            ))}
            {analysts.length === 0 && (
              <tr>
                <td colSpan="6" style={{ padding: '2rem', textAlign: 'center', color: '#888' }}>No analysts found.</td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      {/* --- View Activity Modal --- */}
      {showActivityModal && selectedAnalyst && (
        <div style={{ position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.6)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000 }}>
          <div style={{ backgroundColor: '#fff', padding: '2rem', borderRadius: '12px', width: '100%', maxWidth: '600px', maxHeight: '80vh', display: 'flex', flexDirection: 'column', boxShadow: '0 10px 30px rgba(0,0,0,0.3)' }}>
            
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid #eee', paddingBottom: '1rem', marginBottom: '1rem' }}>
              <div>
                <h2 style={{ margin: '0 0 0.25rem 0', color: '#333' }}>Activity Log: {selectedAnalyst.name}</h2>
                <span style={{ fontSize: '0.9rem', color: '#666' }}>{selectedAnalyst.role} • {selectedAnalyst.email}</span>
              </div>
              <button onClick={() => setShowActivityModal(false)} style={{ background: 'none', border: 'none', fontSize: '1.5rem', cursor: 'pointer', color: '#888' }}>&times;</button>
            </div>

            {/* Scrollable Timeline */}
            <div style={{ overflowY: 'auto', flexGrow: 1, paddingRight: '1rem' }}>
              {activityLogs.filter(log => log.analystId === selectedAnalyst.id).length === 0 ? (
                <div style={{ textAlign: 'center', padding: '2rem', color: '#888' }}>No recent activity found for this user.</div>
              ) : (
                <div style={{ position: 'relative', borderLeft: '2px solid #eee', marginLeft: '1rem', paddingBottom: '1rem' }}>
                  {activityLogs.filter(log => log.analystId === selectedAnalyst.id).map((log, index) => {
                    const style = getLogStyle(log.type);
                    return (
                      <div key={log.id} style={{ position: 'relative', paddingLeft: '2rem', marginBottom: '1.5rem', marginTop: index === 0 ? '1rem' : '0' }}>
                        {/* Timeline Dot */}
                        <div style={{ position: 'absolute', left: '-12px', top: '0', fontSize: '1.2rem', backgroundColor: '#fff', borderRadius: '50%' }}>
                          {style.icon}
                        </div>
                        
                        {/* Log Content */}
                        <div style={{ backgroundColor: '#fafafa', padding: '1rem', borderRadius: '8px', border: '1px solid #f0f0f0' }}>
                          <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.5rem' }}>
                            <strong style={{ color: style.color }}>{log.action}</strong>
                            <span style={{ fontSize: '0.8rem', color: '#888' }}>{log.timestamp}</span>
                          </div>
                          <div style={{ fontSize: '0.9rem', color: '#444' }}>{log.details}</div>
                        </div>
                      </div>
                    )
                  })}
                </div>
              )}
            </div>

            <div style={{ marginTop: '1.5rem', paddingTop: '1rem', borderTop: '1px solid #eee', textAlign: 'right' }}>
              <button onClick={() => window.alert('Exporting CSV...')} style={{ padding: '0.5rem 1rem', backgroundColor: 'transparent', border: '1px solid #2196F3', color: '#2196F3', borderRadius: '4px', cursor: 'pointer', marginRight: '1rem' }}>Export Log (CSV)</button>
              <button onClick={() => setShowActivityModal(false)} style={{ padding: '0.5rem 1rem', backgroundColor: '#f5f5f5', border: '1px solid #ddd', borderRadius: '4px', cursor: 'pointer', color: '#333' }}>Close</button>
            </div>
          </div>
        </div>
      )}

      {/* --- Add Analyst Modal (Unchanged) --- */}
      {showAddModal && (
        <div style={{ position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.5)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000 }}>
          <div style={{ backgroundColor: '#fff', padding: '2rem', borderRadius: '10px', width: '100%', maxWidth: '400px', boxShadow: '0 10px 25px rgba(0,0,0,0.2)' }}>
            <h2 style={{ margin: '0 0 1.5rem 0' }}>Add New Analyst</h2>
            <form onSubmit={handleAddSubmit}>
              <div style={{ marginBottom: '1rem' }}>
                <label style={{ display: 'block', marginBottom: '0.5rem', fontWeight: '500', color: '#555' }}>Full Name</label>
                <input type="text" value={newAnalyst.name} onChange={(e) => setNewAnalyst({...newAnalyst, name: e.target.value})} required style={{ width: '100%', padding: '0.75rem', border: '1px solid #ccc', borderRadius: '4px', boxSizing: 'border-box' }} placeholder="e.g. Jane Doe" />
              </div>
              <div style={{ marginBottom: '1rem' }}>
                <label style={{ display: 'block', marginBottom: '0.5rem', fontWeight: '500', color: '#555' }}>Email Address</label>
                <input type="email" value={newAnalyst.email} onChange={(e) => setNewAnalyst({...newAnalyst, email: e.target.value})} required style={{ width: '100%', padding: '0.75rem', border: '1px solid #ccc', borderRadius: '4px', boxSizing: 'border-box' }} placeholder="jane@cloudshield.local" />
              </div>
              <div style={{ marginBottom: '1.5rem' }}>
                <label style={{ display: 'block', marginBottom: '0.5rem', fontWeight: '500', color: '#555' }}>Role</label>
                <select value={newAnalyst.role} onChange={(e) => setNewAnalyst({...newAnalyst, role: e.target.value})} style={{ width: '100%', padding: '0.75rem', border: '1px solid #ccc', borderRadius: '4px', boxSizing: 'border-box' }}>
                  <option value="Analyst">Analyst</option>
                  <option value="Senior Analyst">Senior Analyst</option>
                </select>
              </div>
              <div style={{ display: 'flex', gap: '1rem', justifyContent: 'flex-end' }}>
                <button type="button" onClick={() => setShowAddModal(false)} style={{ padding: '0.75rem 1.5rem', backgroundColor: 'transparent', border: '1px solid #ccc', borderRadius: '4px', cursor: 'pointer', color: '#555' }}>Cancel</button>
                <button type="submit" style={{ padding: '0.75rem 1.5rem', backgroundColor: '#2196F3', border: 'none', borderRadius: '4px', cursor: 'pointer', color: '#fff', fontWeight: 'bold' }}>Create Account</button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}

export default ManageAnalysts;